tardis_config_version: v1.0
atom_data: "atom_data.h5"
csvy_model: "model.csvy"

supernova:
  luminosity_requested: 9.398 log_lsun
  time_explosion: 11 day

plasma:
  ionization: nebular
  excitation: dilute-lte
  radiative_rates_type: detailed
  line_interaction_type: macroatom
  initial_t_inner: 16000 K

  nlte_ionization_species: [H I, H II, He I, He II]
  continuum_interaction:
    species: [H I, H II, He I, He II]
    enable_adiabatic_cooling: True

montecarlo:
  seed: 23111963
  no_of_packets: 4.0e+4
  iterations: 10

  last_no_of_packets: 1.0e+5
  no_of_virtual_packets: 10
  nthreads: 1

  convergence_strategy:
    type: damped
    stop_if_converged: True
    fraction: 0.9
    hold_iterations: 3
    damping_constant: 0.5
    threshold: 0.05
    t_inner:
      damping_constant: 0.0 # 0.5

spectrum:
  start: 1000 angstrom
  stop: 10000 angstrom
  num: 1000
